### ISSUE TITLE
ちょっとだけ画面を作りこむ

### ISSUE THREAD

**Issue by inaohiro** [inaohiro/test-project#7]
データを view に渡せるようになった (画面に表示させることができるようになった) ので，次はちょっとだけ画面を作っていこう

css とか，画面デザインについてはあまり考える必要はないです :)

以下，view.html.erb の例

```
<div class="today">
  <span class="weather"><%= @data[:today][:weather] %></span>
  <span class="day"><%= @data[:today][:day] %></span>
</div>

<div class="weekly">
  <% @data[:weekly].each do |date| %>
    <div>
      <span class="weather"><%= date[:weather] %></span>
      <span class="day"><%= date[:day %></span>
    </div>
  <% end %>
</div>
```

**Comment by kota-kaihori** [comment]
こんな感じになっています
![image](https://user-images.githubusercontent.com/40154239/42978002-58dac842-8c05-11e8-8dee-86a52410c28f.png)

**Comment by kota-kaihori** [comment]
場所も表示させました
![image](https://user-images.githubusercontent.com/40154239/42984494-ba96ed0a-8c27-11e8-81ba-c928c522c2f7.png)

**Comment by inaohiro** [comment]
#18 デザインが反映された

**Comment by inaohiro** [comment]
画像が取れてない

**Comment by inaohiro** [comment]
画像追加した

**Comment by inaohiro** [comment]
できた
