### ISSUE TITLE
取得した天気データの成形

### ISSUE THREAD

**Issue by inaohiro** [inaohiro/test-project#8]
現在の形をより使いやすく，わかりやすくする

データ構造が分かりやすいと画面 (view) 側で使いやすい
view.html.erb を見て構造を理解しやすい
仕様の変更があった際に，対応しやすい (のではないか)

`@data[0][1]` みたいなのだと，それが何を表しているのかがわからないから，もうちょっとフレンドリーにしようという話です

データ構造の例

```
{
    data: [
        {
            date: "2018/07/10",
            weather: "晴れ",
            temparature: {
                max: "36度",
                min: "30度"
            }
        },
        {
            date: "2018/07/11",
            weather: "晴れのち曇り",
            temparature: {
                max: "32度",
                min: "27度"
            }
        }
    ]
}
```

他にも，today は要素が一つだけ，weekly は配列の中に要素が複数みたいに 使いやすさ，判り易さを求めてアレンジしてもらって構いません :)

**Comment by kota-kaihori** [comment]
取得するページが変わった。
'''
    def setother(doc,other)
        arr = Array.new
        doc.xpath('//td').each do |node|
            s = node.inner_text
            arr.push(s)
        end
        other = arr
    end
    
    def setother2(doc,other2)
        arr = Array.new
        doc.xpath('//th').each do |node|
            s = node.inner_text
            s.gsub!(/\n    /,'')
            s.gsub!(/\n  /,'')
            arr.push(s)
        end
        other2 = arr[7..31]+arr[46..70]
    end
    
    def getdate(other2,date,day_of_the_week)

        for i in 0..9 do
            date[i]=other2[5*i]
        end
          
        for i in 0..9 do
             date[i].sub!(/月/,'/')
             date[i].sub!(/日/,'') 
             day_of_the_week.push(date[i][-2])
             date[i].slice!(-3..-1)
            if date[i][0] == "0" then
                date[i].slice!(0)
            end
        end
    end
    
    def getrainprobability(other2,rainprobability)
        for i in 0..9 do
            rainprobability[i]=other2[5*i+3].delete("%").to_i
        end
    end
    
    def getweather(other,weatherAM,weatherPM)
        for i in 0..39 do
            if i%4 == 1 then
                weatherAM.push(other[i*7+1])
            elsif i%4 == 2 then
                weatherPM.push(other[i*7+1])
            end
        end
    end
    
    def scrape()
        # URLにアクセスするためのライブラリの読み込み
        require 'open-uri'
        # Nokogiriライブラリの読み込み
        require 'nokogiri'
        # スクレイピング先のURL
        url = 'https://tenki.jp/forecast/3/16/4410/13113/10days.html'

        charset = nil
        html = open(url) do |f|
            charset = f.charset # 文字種別を取得
            f.read # htmlを読み込んで変数htmlに渡す
        end

        # htmlをパース(解析)してオブジェクトを生成
        doc = Nokogiri::HTML.parse(html, nil, charset)

        other = Array.new
        other2 = Array.new
        
        date = Array.new(10)
        day_of_the_week = Array.new
        weatherAM= Array.new
        weatherPM= Array.new
        rainprobability = Array.new
        
        other = setother(doc,other)
        other2 = setother2(doc,other2)
        
        getdate(other2,date,day_of_the_week)
        getrainprobability(other2,rainprobability)

        getweather(other,weatherAM,weatherPM)        



        p date
        p rainprobability
        p day_of_the_week
        p weatherAM
        p weatherPM

        # ハッシュ作成
        data = Array.new
        for i in 0..9 do
            data[i]={}
            data[i]["date"]=date[i]
            data[i]["day_of_the_week"]=day_of_the_week[i]
            data[i]["weatherAM"]=weatherAM[i]
            data[i]["weatherPM"]=weatherPM[i]
            data[i]["rainprobability"]=rainprobability[i]
        end
        
        p data
        
    end
    
    scrape()
'''

**Comment by kota-kaihori** [comment]
ハッシュの配列にしました。

"""
[
    {
        "date"=>"7/19",
         "day_of_the_week"=>"木",
         "weatherAM"=>"晴れ",
         "weatherPM"=>"晴れ",
         "rainprobability"=>0
    }, 
    {
         "date"=>"7/20",
         "day_of_the_week"=>"金",
         "weatherAM"=>"晴れ",
         "weatherPM"=>"晴れ",
         "rainprobability"=>0
    },
                         *
                         *
                         *
"""

**Comment by kota-kaihori** [comment]
ハッシュの配列にしました。

"""     
[
     {
          "date"=>"7/19",
          "day_of_the_week"=>"木",
          "weatherAM"=>"晴れ",
          "weatherPM"=>"晴れ",
          "rainprobability"=>0
     },
     {
          "date"=>"7/20",
          "day_of_the_week"=>"金",
          "weatherAM"=>"晴れ",
          "weatherPM"=>"晴れ",
          "rainprobability"=>0
     },
以下同様
"""

**Comment by inaohiro** [comment]
データの成形はよさげ
